In [ ]:
pip install NumPy

In [ ]:
import numpy as np
print(np.__version__)

2.1.3


In [ ]:
#np.array()
import numpy as np
numbers = np.array([10,20,30,40,50])
print(numbers)

[10 20 30 40 50]


In [ ]:
#np.2d array
import numpy as np
numbers = ([1,2,3],[4,5,6])
print(numbers)

([1, 2, 3], [4, 5, 6])


In [ ]:
# 3d array
import numpy as np
n = ([[4,5,6],[7,8,5]],[[9,4,6],[5,6,3]])
print(n)

([[4, 5, 6], [7, 8, 5]], [[9, 4, 6], [5, 6, 3]])


In [ ]:
# examples with strings
import numpy as np
arr = np.array(["Ravi","Hanifa","Sarayu"])
print(arr)
print(arr.dtype)

['Ravi' 'Hanifa' 'Sarayu']
<U6


In [ ]:
arr = np.array([10.5,99.0,88.7],dtype=int)
print(arr)
print(arr.dtype)

[10 99 88]
int64


In [ ]:
import numpy as np
arr = np.array([10.5,99.0,88.7,"b"])
print(arr)
print(arr.dtype)

['10.5' '99.0' '88.7' 'b']
<U32


In [ ]:
# float
arr = np.array([10,99,88],dtype=float)
print(arr)
print(arr.ndim)# HOW MANY SETS WE AREC TAKING THAT IS NDIMENSION

[10. 99. 88.]
1


In [ ]:
# SHAPE SPECIFYING THE ELEMENTS
arr = np.array([10,99,88])
print(arr)
print(arr.shape)

[10 99 88]
(3,)


In [ ]:
# NP.ARRANGE
arr = np.arange(1,11,2)
print(arr)

[1 3 5 7 9]


In [ ]:
#np.arange(start,stop,step)
# np.zeros
arr = np.zeros(5)
print(arr)
arr = np.zeros((2,5))
print(arr)

[0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
#np.full()
arr = np.full(5,8)
print(arr)

[8 8 8 8 8]


In [ ]:
# linspace
import numpy as np
arrange_result = np.arange(0,10,2)
linspace_result = np.linspace(0,10,5)
print("arange:")
print(arrange_result)
print("linspace:")
print(linspace_result)

arange:
[0 2 4 6 8]
linspace:
[ 0.   2.5  5.   7.5 10. ]


In [ ]:
# ravel() which converts   2D matrix in to one dimensional array  or a squence
arr = np.arange(1,11).reshape(5,2,1)
print(arr)
result = arr.ravel()
print(result)

[[[ 1]
  [ 2]]

 [[ 3]
  [ 4]]

 [[ 5]
  [ 6]]

 [[ 7]
  [ 8]]

 [[ 9]
  [10]]]
[ 1  2  3  4  5  6  7  8  9 10]
<built-in method transpose of numpy.ndarray object at 0x78b13dfcf210>


In [ ]:
# transpose of an array
arr = np.array([
    [1,2,3],
    [4,5,6]
])
print(arr)
r = arr.T
print(r)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [ ]:
# size total number of elements in an arry like shape ,size is also an attribute no ()
arr = np.array([
    [10,42,60],
    [20,50,60]
])
print(arr.size)

6


In [ ]:
#dtype is to check the datatype
#conversion of int ->float
arr = np.array([10,20,45],dtype=int)
print(arr)
new_arr = arr.astype(float)
print(new_arr)

# dtype is for declare the datatype
#as type is for following the data type

[10 20 45]
[10. 20. 45.]


In [ ]:
import numpy as np
arr = np.array([10,20,30,40,50,60,70,80,90])
print(arr)
print(arr[0:3])
print(arr[-2:])
print(arr[-3:-1])
print(arr[0:-2])
print(arr[5:])

[10 20 30 40 50 60 70 80 90]
[10 20 30]
[80 90]
[70 80]
[10 20 30 40 50 60 70]
[60 70 80 90]


In [ ]:
#indexing in 2d array
arr = np.array([
    [10,20,30],
    [40,50,60],
    [40,53,60]
])
print(arr[(2,2)])
print(arr[0:2])

60
[[10 20 30]
 [40 50 60]]


In [ ]:
#modification
import numpy as np
arr[1:4] = 23
print(arr)

[[10 20]
 [23 23]]


In [ ]:
# insert single values columns
arr = np.array([
    [10, 20],
    [30, 40]])
result = np.insert(arr,1,[100, 200],axis=1)
print(result)

[[ 10 100  20]
 [ 30 200  40]]


In [ ]:
# insert multiple values rows
arr = np.array([
    [10, 20],
    [30, 40]])
result = np.insert(arr, 1,[100, 200],axis=0)
print(result)

[[ 10  20]
 [100 200]
 [ 30  40]]


In [ ]:
# deletion
arr = np.array([10,20])
new_arr = np.delete(arr,[1,3])
print(new_arr)

NameError: name 'np' is not defined

In [ ]:
#29-08-2025 insert and delete
import numpy as np
arr = np.array([10,20,30,40,50])
n = np.insert(arr,2,25)
print(arr)
print(n)
result = np.delete(arr,1)
print(result)

[10 20 30 40 50]
[10 20 25 30 40 50]
[10 30 40 50]


In [ ]:
import numpy as np
arr = np.array([
    [10, 20,30],
    [30, 40,50]])
result = np.insert(arr, 1,[100, 200,300],axis=0)
print(result)
arr = np.array([
    [10, 20,30],
    [30, 40,50]])
result = np.insert(arr, 1,[100, 200],axis=1)
print(result)

[[ 10  20  30]
 [100 200 300]
 [ 30  40  50]]
[[ 10 100  20  30]
 [ 30 200  40  50]]


In [ ]:
arr = np.delete(arr,0,axis=0)
print(arr)
# for deleting row =0

[]


In [ ]:
arr = np.delete(arr,1,axis=1)
print(arr)
# for deleting column=1

[[30 50]]


In [ ]:
# for numpy aggregates = sum
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
print(np.sum(arr))

150


In [ ]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60]
])
print(arr)
print(np.sum(arr))
print(np.sum(arr,axis=0))
print(np.sum(arr,axis=1))

[[10 20 30]
 [40 50 60]]
210
[50 70 90]
[ 60 150]


In [ ]:
# min()
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
print(np.min(arr))

10


In [ ]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60]
])
print(arr)
print(np.min(arr))
print(np.min(arr,axis=0))
print(np.min(arr,axis=1))

[[10 20 30]
 [40 50 60]]
10
[10 20 30]
[10 40]


In [ ]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60]
])
print(arr)
print(np.max(arr))
print(np.max(arr,axis=0))
print(np.max(arr,axis=1))

[[10 20 30]
 [40 50 60]]
60
[40 50 60]
[30 60]


In [ ]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60]
])
print(arr)
print(np.var(arr))
print(np.var(arr,axis=0))
print(np.var(arr,axis=1))

[[10 20 30]
 [40 50 60]]
291.6666666666667
[225. 225. 225.]
[66.66666667 66.66666667]


In [ ]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60]
])
print(arr)
print(np.std(arr))
print(np.std(arr,axis=0))
print(np.std(arr,axis=1))
# standard deviation is the square root of variance

[[10 20 30]
 [40 50 60]]
17.07825127659933
[15. 15. 15.]
[8.16496581 8.16496581]


In [ ]:
arr = np.array([10, 20, 30,40])
print(arr)
print(np.percentile(arr,[20,30]))
print(np.quantile(arr,0.15))

[10 20 30 40]
[16. 19.]
14.5


In [ ]:
arr = np.array([10, 20, 30,40])
print(arr)
print(np.argmax(arr))

[10 20 30 40]
3
0


In [ ]:
arr = np.array([10, 20, 30,40])
print(arr)
print(np.argmin(arr))

[10 20 30 40]
0


In [ ]:
# log

In [ ]:
# squrt

In [ ]:
# round()
arr = np.array([10.25,20.67,30.49])
print(np.round(arr))

[10. 21. 30.]


In [ ]:
arr = np.array([10.9987,20.6978,30.4896])
print(np.round(arr,3))
#least and highest value

[10.999 20.698 30.49 ]


In [ ]:
arr = np.array([10.9987,20.6978,30.4896])
print(np.floor(arr))
# for least values

[10. 20. 30.]


In [ ]:
arr = np.array([10.9987,20.6978,30.4896])
print(np.ceil(arr))
#for high values

[11. 21. 31.]


In [ ]:
# abs if there are negavtive values that can be changed to positive values
arr = np.array([10,-5,5,20,30,-89])
print(np.abs(arr))

[10  5  5 20 30 89]


In [ ]:
# sorting integer array small to big
arr = np.array([50,30,40,50,60])
result = np.sort(arr)
print(result)

[30 40 50 50 60]


In [ ]:
# ascending order which we use [::-1]
arr = np.array([50,10,20,40])
result = np.sort(arr)[::-1]
print(result)

[50 40 20 10]


In [ ]:
# concatenate  join array in existing table np.concatenate()

In [ ]:
# stack where it creates a new axis like it changes the dimensions two stack
# hstack(), v stack()

In [ ]:
# no chaqnge in dimnesions
import numpy as np
arr_1 = np.array([10,20,30,40])
arr_2 = np.array([45,50,60,70])
result = np.concatenate((arr_1, arr_2))
print(result)

[10 20 30 40 45 50 60 70]


In [ ]:
arr = np.arange(10,20).reshape(2,5)
arr_3 = np.arange(1,11).reshape(2,5)
print(arr)
print(arr_3)
arr_4 = np.concatenate((arr,arr_3))

[[10 11 12 13 14]
 [15 16 17 18 19]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
arr1 = np.array([
    [10, 20],
    [30, 40]
])
arr2 = np.array([
    [50, 60],
    [70, 80]])
result = np.concatenate((arr1, arr2), axis=1)
print(result)
# change in columns increase

[[10 20 50 60]
 [30 40 70 80]]


In [ ]:
arr1 = np.array([
    [10, 20],
    [30, 40]
])
arr2 = np.array([
    [50, 60],
    [70, 80]])
result = np.concatenate((arr1, arr2), axis=0)
print(result)
# no change in dimensions
# row increase
# if you are giving the 1d need to give only in 1d
# same as for 2d and 3d

[[10 20]
 [30 40]
 [50 60]
 [70 80]]


In [ ]:
# stack we can change the dimensions
import numpy as np
arr1 = np.array([10,20,30,40])
arr2 = np.array([45,50,60,70])
result = np.stack((arr1,arr2),axis=0)
print(result)
print(result.ndim)

[[10 20 30 40]
 [45 50 60 70]]
2


In [ ]:
import numpy as np
arr1 = np.array([10,20,30,40])
arr2 = np.array([45,50,60,70])
result = np.stack((arr1,arr2),axis=1)
print(result)
print(result.ndim)

[[10 45]
 [20 50]
 [30 60]
 [40 70]]
2


In [ ]:
import numpy as np
arr1 = np.array([10,20,30,40])
arr2 = np.array([45,50,60,70])
arr3 = np.array([50,75,85,62])
result = np.stack((arr1,arr2,arr3),axis=1)
print(result)
print(result.ndim)

[[10 45 50]
 [20 50 75]
 [30 60 85]
 [40 70 62]]
2


In [ ]:
import numpy as np
arr1 = np.array([10,20,30,40])
arr2 = np.array([45,50,60,70])
arr3 = np.array([50,75,85,62])
result = np.stack((arr1,arr2,arr3),axis=0)
print(result)
print(result.ndim)

[[10 20 30 40]
 [45 50 60 70]
 [50 75 85 62]]
2


In [ ]:
import numpy as np
arr1 = np.array([10,20,30,40])
arr2 = np.array([45,50,60,70])
result = np.vstack((arr1,arr2))
print(result)
print(result.ndim)

[[10 20 30 40]
 [45 50 60 70]]
2


In [ ]:
import numpy as np
arr1 = np.array([10,20,30,40])
arr2 = np.array([45,50,60,70])
arr3 = np.array([52,45,65,32])
result = np.vstack((arr1,arr2,arr3))
print(result)
print(result.ndim)

[[10 20 30 40]
 [45 50 60 70]
 [52 45 65 32]]
2


In [ ]:
import numpy as np
arr1 = np.array([10,20,30,40])
arr2 = np.array([45,50,60,70])
result = np.hstack((arr1,arr2))
print(result)
print(result.ndim)

[10 20 30 40 45 50 60 70]
1


In [ ]:
import numpy as np
arr1 = np.array([10,20,30,40])
arr2 = np.array([45,50,60,70])
arr3 = np.array([25,15,35,45])
result = np.hstack((arr1,arr2,arr3))
print(result)
print(result.ndim)

[10 20 30 40 45 50 60 70 25 15 35 45]
1
